- become: true
  block:
    - name: Check for changes in /etc
      command: git status --porcelain=v1
      args:
        chdir: /etc
      register: git_status
      changed_when: false
      failed_when: false

    - name: All changes in /etc are snap changes?
      shell: |
        git status --porcelain=v1 \
            | cut -c 4- \
            | grep -G -v '^systemd/system/' \
            | grep -G -v '/snap\.\|snap-'
      args:
        chdir: /etc
      register: only_snap
      changed_when: false
      failed_when: false

    - name: Commit changes in /etc
      command: etckeeper commit 'after snap run'
      when: git_status.stdout and only_snap.rc != 0
