- name: Check if snap is installed
  command: snap --version
  register: snap_version
  changed_when: no
  failed_when: no
  ignore_errors: yes

- become: yes
  when: snap_version.rc == 0 and etc_versioned
  block:
    - name: There are uncommitted changes
      command: git status --porcelain=v1
      args:
        chdir: /etc
      register: git_status
      changed_when: no

    - name: All changes are snap changes
      shell: git status --porcelain=v1 | cut -c 4- | grep -G -v '^systemd/system/' | grep -G -v '/snap\.\|snap-'
      args:
        chdir: /etc
      register: only_snap
      changed_when: no
      ignore_errors: yes
  
    - name: Commit snap changes
      command: etckeeper commit 'after snap run'
      when: git_status.stdout and only_snap.rc != 0
