- name: Check if yay is installed
  command: yay --version
  register: yay_version
  changed_when: false
  failed_when: false

- when: yay_version.rc == 0
  block:
    - name: Upgrade packages
      kewlfft.aur.aur:
        use: yay
        update_cache: true
        upgrade: true
        aur_only: true
      register: yay_result
      notify: reboot

    - debug:
        var: yay_result
      when: yay_result

    - name: Flush handlers
      meta: flush_handlers
