- name: Check if apt is installed
  command: apt-get --version
  register: apt_version
  changed_when: no
  failed_when: no

- when: apt_version.rc == 0
  become: yes
  block:
    - name: Upgrade packages
      apt:
        update_cache: yes
        upgrade: full
      notify: reboot

    - name: Flush handlers
      meta: flush_handlers

    - name: Clean up dependencies
      apt:
        autoremove: yes
        purge: yes
      notify: reboot

    - name: Flush handlers
      meta: flush_handlers
