- name: Update plugins
  command: vagrant plugin update

- name: Prune invalid entries
  command: vagrant global-status --prune
  become: true

- name: Clean up boxes
  command: vagrant box prune --force --keep-active-boxes
