- name: Check if vagrant is installed
  command: vagrant --version
  register: vagrant_version
  changed_when: no
  failed_when: no
  ignore_errors: yes

- when: vagrant_version.rc == 0
  block:
    - name: Update plugins
      command: vagrant plugin update

    - name: Prune invalid entries
      command: vagrant global-status --prune

    - name: Clean up boxes
      command: vagrant box prune --force --keep-active-boxes
