- name: Check if vagrant is installed
  command: vagrant --version
  register: vagrant_version
  changed_when: false
  failed_when: false

- when: vagrant_version.rc == 0
  block:
    - name: Update plugins
      command: vagrant plugin update

    - name: Prune invalid entries
      command: vagrant global-status --prune
      become: true

    - name: Clean up boxes
      command: vagrant box prune --force --keep-active-boxes
