- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
  notify: reboot

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Clean up dependencies
  become: true
  ansible.builtin.apt:
    autoremove: true
    purge: true
  notify: reboot

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
