- name: Upgrade packages
  kewlfft.aur.aur:
    use: yay
    update_cache: true
    upgrade: true
    aur_only: true
  register: yay_result
  notify: reboot

- name: Show yay result
  ansible.builtin.debug:
    var: yay_result
  when: yay_result

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
