- name: Make sure git is configured
  become: true
  block:
    - name: Set user.name
      community.general.git_config:
        scope: local
        repo: /etc
        name: user.name
        value: '{{ git_name }}'

    - name: Set user.email
      community.general.git_config:
        scope: local
        repo: /etc
        name: user.email
        value: '{{ git_email }}'
