name: yandex-cloud-cli-bin

on:
  workflow_call:
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm git openssh
      - name: Add SSH key
        run: |
          mkdir -p /root/.ssh/
          cat > /root/.ssh/config <<'EOF'
          StrictHostKeyChecking no
          EOF
          cat > /root/.ssh/id_ed25519 <<'EOF'
          ${{ secrets.SSH_KEY }}
          EOF
          chmod 0600 /root/.ssh/id_ed25519
      - name: Checkout
        run: |
          git clone -q ssh://aur@aur.archlinux.org/yandex-cloud-cli-bin.git
          chmod -R o+w yandex-cloud-cli-bin
      - name: Configure git
        run: |
          # Stupid GitHub Actions sets $HOME to something else other than /root
          # when using container:, which breaks everything.
          git -C yandex-cloud-cli-bin config --local user.name 'Egor Tensin'
          git -C yandex-cloud-cli-bin config --local user.email 'egor@tensin.name'
      - name: Run maintenance
        run: |
          git config --system --add safe.directory "$( pwd )/yandex-cloud-cli-bin"
          # Stupid makepkg hard forbids running as root, which is stupid, which
          # is why I'm doing all of that stupidity here and above.
          runuser -u nobody -- make -C yandex-cloud-cli-bin maintenance
